Repository boring-km/UntakenGoodsManagerApp, pull requests merged in 2021-03, with the labels that each got.

#1 Create README.md
  README.md
Labels: duplicate

#2 [JKM] QR Code 데이터 생성을 위한 SHA256 알고리즘 테스트
  .gradle/6.1.1/executionHistory/executionHistory.bin
  .gradle/6.1.1/executionHistory/executionHistory.lock
  .gradle/6.1.1/fileHashes/fileHashes.bin
  .gradle/6.1.1/fileHashes/fileHashes.lock
  .gradle/6.1.1/fileHashes/resourceHashesCache.bin
  .gradle/6.1.1/javaCompile/classAnalysis.bin
  .gradle/6.1.1/javaCompile/jarAnalysis.bin
  .gradle/6.1.1/javaCompile/javaCompile.lock
  .gradle/6.1.1/javaCompile/taskHistory.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/checksums/checksums.lock
  .gradle/checksums/md5-checksums.bin
  .gradle/checksums/sha1-checksums.bin
  .idea/assetWizardSettings.xml
  .idea/caches/build_file_checksums.ser
  .idea/libraries/Gradle__org_apiguardian_apiguardian_api_1_0_0_jar.xml
  .idea/libraries/Gradle__org_junit_jupiter_junit_jupiter_5_4_2_jar.xml
  .idea/libraries/Gradle__org_junit_jupiter_junit_jupiter_api_5_4_2_jar.xml
  .idea/libraries/Gradle__org_junit_jupiter_junit_jupiter_params_5_4_2_jar.xml
  .idea/libraries/Gradle__org_junit_platform_junit_platform_commons_1_4_2_jar.xml
  .idea/libraries/Gradle__org_opentest4j_opentest4j_1_1_1_jar.xml
  .idea/modules/app/UntakenGoodsManagerApp.app.iml
  .idea/workspace.xml
  app/build.gradle
  app/src/main/java/com/emart24/InputActivity.kt
  app/src/main/java/com/emart24/MainActivity.kt
  app/src/main/java/com/emart24/ProductListActivity.kt
  app/src/main/res/drawable-hdpi/ic_format_list_bulleted.png
  app/src/main/res/drawable-hdpi/image.9.png
  app/src/main/res/drawable-mdpi/ic_format_list_bulleted.png
  app/src/main/res/drawable-mdpi/image.9.png
  app/src/main/res/drawable-xhdpi/ic_format_list_bulleted.png
  app/src/main/res/drawable-xhdpi/image.9.png
  app/src/main/res/drawable-xxhdpi/ic_format_list_bulleted.png
  app/src/main/res/drawable-xxhdpi/image.9.png
  app/src/main/res/drawable-xxxhdpi/ic_format_list_bulleted.png
  app/src/main/res/drawable-xxxhdpi/image.9.png
  app/src/main/res/layout/activity_list.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/emart24/ExampleUnitTest.kt
  app/src/test/java/com/emart24/RegisterTest.kt
Labels: enhancement

#4 [JKM] QR코드 라이브러리 사용 코드를 리팩토링 한다
  app/src/main/java/com/emart24/CreateQRActivity.kt
  app/src/main/java/com/emart24/InputActivity.kt
  app/src/main/java/com/emart24/ScanQRActivity.kt
  app/src/main/java/com/emart24/component/GoodsComponent.kt
  app/src/main/java/com/emart24/service/GoodsModule.kt
  app/src/main/java/com/emart24/service/GoodsService.kt
  app/src/main/java/com/emart24/service/QRService.kt
Labels: 리팩토링

#5 [JKM] Dagger 오류 수정
  app/.gitignore
  app/google-services.json
  app/src/main/java/com/emart24/CreateQRActivity.kt
  app/src/main/java/com/emart24/MainActivity.kt
  app/src/main/java/com/emart24/ScanQRActivity.kt
  app/src/main/java/com/emart24/service/GoodsService.kt
  app/src/main/java/com/emart24/service/QRService.kt
Labels: bug

#6 [JJW] QR코드 스캔 시 예외상황 처리 및 화면 버튼 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/emart24/CreateQRActivity.kt
  app/src/main/java/com/emart24/InputActivity.kt
  app/src/main/java/com/emart24/MainActivity.kt
  app/src/main/java/com/emart24/ScanQRActivity.kt
  app/src/main/res/layout/activity_create_qr.xml
  app/src/main/res/layout/activity_register.xml
Labels: bug, enhancement

#7 [JKM] 상품 리스트로 조회 화면 구현
  .idea/render.experimental.xml
  app/src/main/java/com/emart24/CreateQRActivity.kt
  app/src/main/java/com/emart24/GoodsResultActivity.kt
  app/src/main/java/com/emart24/InputActivity.kt
  app/src/main/java/com/emart24/ProductListActivity.kt
  app/src/main/java/com/emart24/ScanQRActivity.kt
  app/src/main/java/com/emart24/adapter/ProductListAdapter.kt
  app/src/main/java/com/emart24/component/GoodsComponent.kt
  app/src/main/java/com/emart24/model/UnTakenGoods.kt
  app/src/main/java/com/emart24/service/GoodsService.kt
  app/src/main/res/layout/activity_accept.xml
  app/src/main/res/layout/activity_list.xml
  app/src/main/res/layout/product_list_item.xml
Labels: enhancement

#8 [JKM] 1차 완성
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/emart24/GoodsResultActivity.kt
  app/src/main/java/com/emart24/InputActivity.kt
  app/src/main/java/com/emart24/ProductDetailActivity.kt
  app/src/main/java/com/emart24/ProductListActivity.kt
  app/src/main/java/com/emart24/ScanQRActivity.kt
  app/src/main/java/com/emart24/adapter/ProductListAdapter.kt
  app/src/main/java/com/emart24/component/GoodsComponent.kt
  app/src/main/java/com/emart24/model/UnTakenGoods.kt
  app/src/main/java/com/emart24/service/GoodsService.kt
  app/src/main/java/com/emart24/service/QRService.kt
  app/src/main/res/layout/activity_accept.xml
  app/src/main/res/layout/activity_create_qr.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/product_list_item.xml
  app/src/test/java/com/emart24/RegisterTest.kt
Labels: enhancement
